# Numpy

In [4]:
# %pip install numpy
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## 2D array


In [6]:
a_list = [
    [1,2,3,4],
    [5,4,6,7],
    [9,10,11,12]
]

In [16]:
print (a_list )
print (a_list[1][2] )
print (a_list[2] )
print ( [ row[0] for row in a_list ] )

[[1, 2, 3, 4], [5, 4, 6, 7], [9, 10, 11, 12]]
6
[9, 10, 11, 12]
[1, 5, 9]


In [13]:
import numpy as np

In [17]:
np_array = np.array(a_list)
print(np_array)
print(type(np_array))

[[ 1  2  3  4]
 [ 5  4  6  7]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


In [29]:
print (np_array[0] )
print (np_array[0][2] )
print (np_array[0, 2] ) # [ row index, column index ]
print (np_array[:, 2], '\n' )
print (np_array[:, 3], '\n' )

print (np_array[1:, 1:3], '\n' )

print (np_array[ 1, [0,3]], '\n' )

[1 2 3 4]
3
3
[ 3  6 11] 

[ 4  7 12] 

[[ 4  6]
 [10 11]] 

[5 7] 



In [33]:
print( np_array)
print( np_array.shape )
print( len(np_array) )
print( len(np_array[0]) )

[[ 1  2  3  4]
 [ 5  4  6  7]
 [ 9 10 11 12]]
(3, 4)
3
4


## 1D array

In [42]:
array_1d = np.array( [1,58,97,3,74] )
print(array_1d)
list_1d = [1,58,97,3,74]
print(list_1d * 3)
print([ num * 3 for num in list_1d])
print('numpy array')
print(array_1d * 3 )
print(array_1d + 3 )
print(array_1d / 3 )
print(array_1d % 3 )
print(array_1d ** 3 )

[ 1 58 97  3 74]
[1, 58, 97, 3, 74, 1, 58, 97, 3, 74, 1, 58, 97, 3, 74]
[3, 174, 291, 9, 222]
numpy array
[  3 174 291   9 222]
[  4  61 100   6  77]
[ 0.33333333 19.33333333 32.33333333  1.         24.66666667]
[1 1 1 0 2]
[     1 195112 912673     27 405224]


In [49]:
array_1d = np.array( [1,58,97,3,74] )
print(array_1d)
list_1d = [1,58,97,3,74]
list_1d[2:4] = [10,25]
print(list_1d)
# list_1d[2:4] = 50 # error
list_1d[2:4] = [50, 50 ]
print(list_1d)

array_1d[2:4] = [10,25]
print(array_1d)
array_1d[2:4] = 50
print(array_1d)

[ 1 58 97  3 74]
[1, 58, 10, 25, 74]
[1, 58, 50, 50, 74]
[ 1 58 10 25 74]
[ 1 58 50 50 74]


## 3D array

In [50]:
arr_3d = np.array([
        [ 
            [1, 2, 3], 
            [4, 5, 6]
        ],
        [
            [1, 2, 3],
            [4, 5, 6]
        ]
    ]
)
print (arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [51]:
print(arr_3d.shape)

(2, 2, 3)


In [54]:
arr_3d[ :, :, 2 ] = 10
print(arr_3d, '\n')
# replace 2nd matrix 1st row 1st and 2nd column values with 50
arr_3d[1, 0, 0:2] = 50
print(arr_3d)

[[[ 1  2 10]
  [ 4  5 10]]

 [[50 50 10]
  [ 4  5 10]]] 

[[[ 1  2 10]
  [ 4  5 10]]

 [[50 50 10]
  [ 4  5 10]]]


## Numpy speed

In [55]:
size = 1_000_000

In [58]:
# %%timeit # Jupyter command

py_list = list(range(size)) # ~15 ms

In [59]:
len(py_list)

1000000

In [61]:
%%timeit

np_arr = np.arange(size) # ~1 ms

1.25 ms ± 10.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [62]:
%%timeit
[ num * 2 for num in py_list]

56 ms ± 731 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [63]:
%%timeit
np_arr * 2

1.25 ms ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Numpy reshape

In [64]:
np_arr = np.arange(100)
print(np_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [65]:
print( np_arr.reshape( (10, 10) ) )

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [66]:
print( np_arr.reshape( (4,5,5) ) )

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [67]:
print( np_arr.reshape( (5, 10, -1) ) )


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]
  [30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]
  [50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]
  [66 67]
  [68 69]
  [70 71]
  [72 73]
  [74 75]
  [76 77]
  [78 79]]

 [[80 81]
  [82 83]
  [84 85]
  [86 87]
  [88 89]
  [90 91]
  [92 93]
  [94 95]
  [96 97]
  [98 99]]]


## Numpy methods and functions

In [68]:
array_3d = np.array( [
    [ [1,2], [4,3], [7,4] ],
    [ [2,2], [4,3], [7,4] ],
    [ [3,2], [4,3], [7,4] ],
    [ [4,2], [4,3], [7,4] ],
]
)
print(array_3d.shape)

(4, 3, 2)


In [69]:
print(array_3d)

[[[1 2]
  [4 3]
  [7 4]]

 [[2 2]
  [4 3]
  [7 4]]

 [[3 2]
  [4 3]
  [7 4]]

 [[4 2]
  [4 3]
  [7 4]]]


In [76]:
print( array_3d.mean() )
print( np.mean(array_3d)  )

print( 'Matrix mean\n', array_3d.mean(axis=0 ), '\n' )
print( 'Column mean\n', array_3d.mean(axis=1 ), '\n' )
print( 'Row mean\n', array_3d.mean(axis=2 ), '\n' )

3.75
3.75
Matrix mean
 [[2.5 2. ]
 [4.  3. ]
 [7.  4. ]] 

Column mean
 [[4.         3.        ]
 [4.33333333 3.        ]
 [4.66666667 3.        ]
 [5.         3.        ]] 

Row mean
 [[1.5 3.5 5.5]
 [2.  3.5 5.5]
 [2.5 3.5 5.5]
 [3.  3.5 5.5]] 



In [78]:
print( 'Row sum\n', array_3d.sum(axis=2 ), '\n' )
print( 'Column std\n', array_3d.std(axis=1 ), '\n' )

Row sum
 [[ 3  7 11]
 [ 4  7 11]
 [ 5  7 11]
 [ 6  7 11]] 

Column std
 [[2.44948974 0.81649658]
 [2.05480467 0.81649658]
 [1.69967317 0.81649658]
 [1.41421356 0.81649658]] 



In [84]:
print(array_3d)
print( 'Column max value\n', array_3d.max(axis=1 ), '\n' )
print( 'Column min value\n', array_3d.min(axis=1 ), '\n' )
print( 'Overall min value\n', array_3d.min(), '\n' )

[[[1 2]
  [4 3]
  [7 4]]

 [[2 2]
  [4 3]
  [7 4]]

 [[3 2]
  [4 3]
  [7 4]]

 [[4 2]
  [4 3]
  [7 4]]]
Column max value
 [[7 4]
 [7 4]
 [7 4]
 [7 4]] 

Column min value
 [[1 2]
 [2 2]
 [3 2]
 [4 2]] 

Overall min value
 1 



In [88]:
print(array_3d.shape)
print(array_3d.T.shape)
print(array_3d.T)

(4, 3, 2)
(2, 3, 4)
[[[1 2 3 4]
  [4 4 4 4]
  [7 7 7 7]]

 [[2 2 2 2]
  [3 3 3 3]
  [4 4 4 4]]]


## Numpy comparison

In [100]:
rand_array = np.random.randint( 5,50, (10,10) )
print(rand_array)
print(rand_array.shape)

[[17 43 44 34 15 34 28 41 23 48]
 [10 35 33 44 18 49 32 34 16 19]
 [19 24  8 17 16 32 36 17 42 20]
 [21 10 35 38 47 37 42 49 10 44]
 [40  7 38 45 39 26 24 41 19  6]
 [14 16 18 23 33 31 29 34 34  9]
 [26 23  5 26 10 11 44  9 41 32]
 [39 22 24 12 38 10 34 36 46 40]
 [20 49 24 46 19 28 17 30 39 44]
 [26 47 30 46 23 34 31 31 11 49]]
(10, 10)


In [97]:
print( rand_array > 15 ) # This is called a mask

[[ True  True False  True  True False  True False  True  True]
 [ True  True  True  True  True False  True  True  True  True]
 [False  True  True False  True  True  True  True  True  True]
 [ True  True  True  True False  True  True  True  True  True]
 [ True  True  True  True False  True  True  True  True  True]
 [False  True  True  True  True  True  True False  True  True]
 [ True  True  True  True False  True False False  True  True]
 [False  True  True  True  True  True False  True  True  True]
 [ True  True False False  True  True  True  True False  True]
 [ True  True False  True False False  True  True  True  True]]


In [99]:
print(rand_array[ rand_array > 15 ] )
print(rand_array[ rand_array > 15 ].shape )

[29 30 35 20 19 48 26 18 45 38 49 31 33 34 35 41 26 30 35 36 33 44 29 43
 20 27 43 45 31 49 35 24 42 46 43 29 35 25 43 34 27 31 42 42 29 41 36 33
 46 39 19 32 26 16 44 47 25 27 47 32 38 24 21 43 40 44 41 29 37 20 43 34
 36 36 37 39 33 33 42]
(79,)


In [102]:
print(rand_array[ rand_array > 45 ] )

[48 49 47 49 46 49 46 47 46 49]


In [103]:
print(rand_array[ rand_array % 2 == 0 ] )

[44 34 34 28 48 10 44 18 32 34 16 24  8 16 32 36 42 20 10 38 42 10 44 40
 38 26 24  6 14 16 18 34 34 26 26 10 44 32 22 24 12 38 10 34 36 46 40 20
 24 46 28 30 44 26 30 46 34]


## iterating numpy array

In [104]:
print(array_3d)

[[[1 2]
  [4 3]
  [7 4]]

 [[2 2]
  [4 3]
  [7 4]]

 [[3 2]
  [4 3]
  [7 4]]

 [[4 2]
  [4 3]
  [7 4]]]


In [108]:
for matrix in array_3d:
    print('loop iteration')
    print(matrix)
    for row in matrix:
        for col in row:
            print(col)

loop iteration
[[1 2]
 [4 3]
 [7 4]]
1
2
4
3
7
4
loop iteration
[[2 2]
 [4 3]
 [7 4]]
2
2
4
3
7
4
loop iteration
[[3 2]
 [4 3]
 [7 4]]
3
2
4
3
7
4
loop iteration
[[4 2]
 [4 3]
 [7 4]]
4
2
4
3
7
4


# Pandas

In [110]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [111]:
import pandas as pd

In [113]:
df = pd.DataFrame(
    [ ['Jan',58,42,74,22,2.05],
    ['Feb',61,45,78,26,3.02],
    ['Mar',65,48,84,25,2.34],
    ['Apr',67,50,92,28,1.02],
    ['May',71,53,98,35,0.48],
    ['Jun',75,56,107,41,0.11],
    ['Jul',77,58,105,44,0.0],
    ['Aug',77,59,102,43,0.03],
    ['Sep',77,57,103,40,0.17],
    ['Oct',73,54,96,34,0.81],
    ['Nov',64,48,84,30,1.7],
    ['Dec',58,None,None,21,2.56],
    ['Dec',58,42,73,21,2.56] ],
    columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

df

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
1    Feb        61     45.0         78.0          26               3.02
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   month              13 non-null     object 
 1   avg_high           13 non-null     int64  
 2   avg_low            12 non-null     float64
 3   record_high        12 non-null     float64
 4   record_low         13 non-null     int64  
 5   avg_precipitation  13 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 752.0+ bytes


In [115]:
df.describe()

avg_high    avg_low  record_high  record_low  avg_precipitation
count  13.000000  12.000000    12.000000   13.000000          13.000000
mean   67.769231  51.000000    91.333333   31.538462           1.296154
std     7.639305   6.060303    12.323911    8.501131           1.115210
min    58.000000  42.000000    73.000000   21.000000           0.000000
25%    61.000000  47.250000    82.500000   25.000000           0.170000
50%    67.000000  51.500000    94.000000   30.000000           1.020000
75%    75.000000  56.250000   102.250000   40.000000           2.340000
max    77.000000  59.000000   107.000000   44.000000           3.020000

In [116]:
df.head()

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34
3   Apr        67     50.0         92.0          28               1.02
4   May        71     53.0         98.0          35               0.48

In [117]:
df.head(3)

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34

In [118]:
df.tail(3)

month  avg_high  avg_low  record_high  record_low  avg_precipitation
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56